const canvas=document.getElementById("game"),ctx=canvas.getContext("2d");
const WIDTH=canvas.width,HEIGHT=canvas.height,WORLD_WIDTH=3300,FLOOR_Y=620;
let audioCtx=null,musicOn=false;
const state={mode:"start",cameraX:0,codeDigits:["4","2","1"],collectedDigits:[],confetti:[],foam:[],bonusBones:0,captureTimer:0,captureBy:null};
const controls={left:false,right:false,jump:false};
const player={x:110,y:FLOOR_Y-108,w:56,h:108,vx:0,vy:0,speed:5.4,jumpPower:16.5,onGround:false,facing:1,anim:0};
const gravity=.78,friction=.82;
const groundSegments=[{x:0,w:500},{x:610,w:520},{x:1240,w:450},{x:1820,w:480},{x:2410,w:420},{x:2920,w:380}];
const platforms=[{x:330,y:550,w:130,h:18},{x:550,y:480,w:120,h:18},{x:760,y:405,w:120,h:18},{x:980,y:340,w:150,h:18},{x:1290,y:545,w:130,h:18},{x:1490,y:470,w:120,h:18},{x:1710,y:395,w:140,h:18},{x:1940,y:320,w:150,h:18},{x:2210,y:255,w:130,h:18},{x:2480,y:500,w:130,h:18},{x:2680,y:430,w:120,h:18},{x:2870,y:350,w:150,h:18},{x:3090,y:270,w:120,h:18}];
const movingPlatforms=[{x:2360,y:390,w:120,h:18,baseY:390,range:65,speed:.022,t:0},{x:2990,y:470,w:120,h:18,baseY:470,range:78,speed:.028,t:1.3}];
const candles=[{homeX:576,homeY:436,x:576,y:436,w:22,h:38,collected:false,digit:"4"},{homeX:1728,homeY:351,x:1728,y:351,w:22,h:38,collected:false,digit:"2"},{homeX:3118,homeY:226,x:3118,y:226,w:22,h:38,collected:false,digit:"1"}];
const dogs=[{x:860,y:FLOOR_Y-40,w:76,h:40,minX:750,maxX:1080,dir:1,speed:1.9,color:"brown"},{x:2570,y:FLOOR_Y-42,w:78,h:42,minX:2460,maxX:2800,dir:-1,speed:2.2,color:"white"}];
const bones=[{homeX:405,homeY:520,x:405,y:520,taken:false},{homeX:1040,homeY:305,x:1040,y:305,taken:false},{homeX:1985,homeY:285,x:1985,y:285,taken:false},{homeX:2925,homeY:315,x:2925,y:315,taken:false}];
const goal={x:3190,y:404,w:110,h:190,burst:false};
const clouds=[{x:140,y:95,s:1.15},{x:480,y:135,s:1.0},{x:880,y:105,s:1.12},{x:1280,y:145,s:1.05},{x:1760,y:110,s:1.14},{x:2230,y:135,s:1.0},{x:2860,y:115,s:1.15}];
const hills=[{x:0,w:540,h:180,c1:"#bee79c",c2:"#97cf73"},{x:430,w:620,h:215,c1:"#c8edaa",c2:"#9ad375"},{x:1040,w:590,h:190,c1:"#bfe99d",c2:"#95cf72"},{x:1580,w:610,h:220,c1:"#caefab",c2:"#9bd375"},{x:2200,w:600,h:185,c1:"#bfe99d",c2:"#95cf72"},{x:2730,w:650,h:205,c1:"#c7edaa",c2:"#9ad375"}];
function ensureAudio(){if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==="suspended")audioCtx.resume()}
function playNote(freq,start,duration,volume=.04){const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type="triangle";o.frequency.value=freq;g.gain.setValueAtTime(.0001,start);g.gain.exponentialRampToValueAtTime(volume,start+.02);g.gain.exponentialRampToValueAtTime(.0001,start+duration);o.connect(g);g.connect(audioCtx.destination);o.start(start);o.stop(start+duration+.03)}
function startMusic(){if(musicOn)return;ensureAudio();musicOn=true;const melody=[392,392,440,392,523,494,392,392,440,392,587,523,392,392,784,659,523,494,440,698,698,659,523,587,523],beat=.30;let nextAt=audioCtx.currentTime+.25;function schedule(){melody.forEach((n,i)=>playNote(n,nextAt+i*beat,beat*.76,.035));nextAt+=melody.length*beat+.5;setTimeout(schedule,(melody.length*beat+.2)*1000)}schedule()}
function resetPlayerPosition(){player.x=110;player.y=FLOOR_Y-player.h;player.vx=0;player.vy=0;player.onGround=false;state.cameraX=0}
function startGame(){state.mode="playing";startMusic()}
function intersects(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function dropCollectedItems(){candles.forEach(c=>{if(c.collected){c.collected=false;c.x=c.homeX;c.y=c.homeY}});state.collectedDigits=[];bones.forEach(b=>{if(b.taken){b.taken=false;b.x=b.homeX;b.y=b.homeY}});state.bonusBones=0}
function beginCapture(dog){if(state.captureTimer>0||state.mode!=="playing")return;state.captureTimer=70;state.captureBy=dog;player.vx=0;player.vy=0;dropCollectedItems()}
function handleInput(){if(state.mode!=="playing"||state.captureTimer>0)return;if(controls.left){player.vx=-player.speed;player.facing=-1}else if(controls.right){player.vx=player.speed;player.facing=1}else{player.vx*=friction;if(Math.abs(player.vx)<.08)player.vx=0}if(controls.jump&&player.onGround){player.vy=-player.jumpPower;player.onGround=false;controls.jump=false}}
function updateMovingPlatforms(){movingPlatforms.forEach(p=>{p.t+=p.speed;p.y=p.baseY+Math.sin(p.t)*p.range})}
function getColliders(){const cols=[];groundSegments.forEach(g=>cols.push({x:g.x,y:FLOOR_Y,w:g.w,h:HEIGHT-FLOOR_Y,kind:"ground"}));platforms.forEach(p=>cols.push({...p,kind:"platform"}));movingPlatforms.forEach(p=>cols.push({x:p.x,y:p.y,w:p.w,h:p.h,kind:"moving"}));return cols}
function updateDogs(){dogs.forEach(d=>{if(!(state.captureTimer>0&&state.captureBy===d)){d.x+=d.speed*d.dir;if(d.x<=d.minX||d.x+d.w>=d.maxX)d.dir*=-1}if(state.mode==="playing"&&state.captureTimer===0&&intersects(player,d))beginCapture(d)})}
function triggerGoalExplosion(){if(goal.burst)return;goal.burst=true;for(let i=0;i<30;i++)state.foam.push({x:goal.x+56,y:goal.y+22,vx:1.8+Math.random()*6.4,vy:-8-Math.random()*5.8,r:5+Math.random()*5,life:85+Math.random()*30});const colors=["#ffd166","#6dd3ff","#7ee081","#ff8ec7","#8f7cff","#ffffff"];for(let i=0;i<180;i++)state.confetti.push({x:goal.x+56,y:goal.y+30,vx:-5+Math.random()*10,vy:-8+Math.random()*-3,size:5+Math.random()*8,rot:Math.random()*Math.PI,vr:-.25+Math.random()*.5,color:colors[Math.floor(Math.random()*colors.length)]})}
function updateCapture(){if(state.captureTimer<=0)return;state.captureTimer-=1;const d=state.captureBy;if(d){player.x=d.x+d.w*.18;player.y=d.y-player.h+6}if(state.captureTimer<=0){state.captureBy=null;resetPlayerPosition()}}
function updatePlayer(){if(state.captureTimer>0){updateMovingPlatforms();updateCapture();return}handleInput();updateMovingPlatforms();player.anim+=Math.abs(player.vx)*.16;player.vy+=gravity;player.x+=player.vx;player.y+=player.vy;if(player.x<0)player.x=0;if(player.x+player.w>WORLD_WIDTH)player.x=WORLD_WIDTH-player.w;player.onGround=false;getColliders().forEach(c=>{if(player.x+player.w>c.x&&player.x<c.x+c.w&&player.y+player.h>=c.y&&player.y+player.h-player.vy<=c.y+9&&player.vy>=0){player.y=c.y-player.h;player.vy=0;player.onGround=true}});if(player.y>HEIGHT+120)resetPlayerPosition();candles.forEach(c=>{if(!c.collected&&intersects(player,c)){c.collected=true;state.collectedDigits.push(c.digit)}});bones.forEach(b=>{const r={x:b.x,y:b.y,w:30,h:16};if(!b.taken&&intersects(player,r)){b.taken=true;state.bonusBones+=1}});if(state.collectedDigits.length===3&&intersects(player,goal)){triggerGoalExplosion();state.mode="win"}state.cameraX=Math.max(0,Math.min(player.x-WIDTH*.33,WORLD_WIDTH-WIDTH))}
function updateParticles(){state.foam.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.vy+=.18;p.life-=1});state.confetti.forEach(c=>{c.x+=c.vx;c.y+=c.vy;c.vy+=.17;c.rot+=c.vr})}
function roundedRect(x,y,w,h,r,fill=true,stroke=false){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);if(fill)ctx.fill();if(stroke)ctx.stroke()}
function drawSky(){const g=ctx.createLinearGradient(0,0,0,HEIGHT);g.addColorStop(0,"#77d5ff");g.addColorStop(.62,"#d8f6ff");g.addColorStop(1,"#ffe2c9");ctx.fillStyle=g;ctx.fillRect(0,0,WIDTH,HEIGHT);ctx.fillStyle="#ffe57a";ctx.beginPath();ctx.arc(1120,90,46,0,Math.PI*2);ctx.fill();hills.forEach(h=>drawHill(h.x-state.cameraX*.42,h.w,h.h,h.c1,h.c2));clouds.forEach(c=>drawCloud(c.x-state.cameraX*.22,c.y,c.s))}
function drawCloud(x,y,s){ctx.fillStyle="rgba(255,255,255,0.97)";ctx.beginPath();ctx.arc(x,y,24*s,0,Math.PI*2);ctx.arc(x+27*s,y-12*s,31*s,0,Math.PI*2);ctx.arc(x+65*s,y,24*s,0,Math.PI*2);ctx.arc(x+34*s,y+10*s,26*s,0,Math.PI*2);ctx.fill();ctx.strokeStyle="rgba(0,0,0,0.12)";ctx.lineWidth=2;ctx.stroke()}
function drawHill(x,w,h,c1,c2){ctx.fillStyle=c1;ctx.beginPath();ctx.moveTo(x,FLOOR_Y+16);ctx.quadraticCurveTo(x+w*.35,FLOOR_Y-h,x+w,FLOOR_Y+16);ctx.closePath();ctx.fill();ctx.fillStyle=c2;ctx.beginPath();ctx.moveTo(x+40,FLOOR_Y+20);ctx.quadraticCurveTo(x+w*.45,FLOOR_Y-h*.65,x+w-28,FLOOR_Y+20);ctx.closePath();ctx.fill()}
function drawGround(){groundSegments.forEach(g=>{const x=g.x-state.cameraX;ctx.fillStyle="#8f5d45";ctx.fillRect(x,FLOOR_Y,g.w,HEIGHT-FLOOR_Y);ctx.fillStyle="#69be67";ctx.fillRect(x,FLOOR_Y,g.w,18);ctx.fillStyle="#ae7357";for(let i=0;i<g.w;i+=40){ctx.fillRect(x+i+4,FLOOR_Y+30,18,8);ctx.fillRect(x+i+17,FLOOR_Y+58,14,8);ctx.fillRect(x+i+6,FLOOR_Y+86,16,8)}})}
function drawPlatformShape(x,y,w,h,fill1,fill2,stroke){ctx.fillStyle=fill1;ctx.strokeStyle=stroke;ctx.lineWidth=4;roundedRect(x,y,w,h,11,true,true);ctx.fillStyle=fill2;roundedRect(x+6,y+4,w-12,h-8,9,true,false)}
function drawPlatforms(){platforms.forEach(p=>drawPlatformShape(p.x-state.cameraX,p.y,p.w,p.h,"#ffffff","#ffd9ea","#7d4b74"));movingPlatforms.forEach(p=>drawPlatformShape(p.x-state.cameraX,p.y,p.w,p.h,"#fff7dc","#ffe18a","#8a6b2e"))}
function drawBone(b){if(b.taken)return;const x=b.x-state.cameraX,y=b.y;ctx.fillStyle="#fff0d7";roundedRect(x,y,30,16,6,true,false);[3,27].forEach(px=>{ctx.beginPath();ctx.arc(x+px,y+4,5,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(x+px,y+12,5,0,Math.PI*2);ctx.fill()});ctx.strokeStyle="#caa16a";ctx.lineWidth=2;roundedRect(x,y,30,16,6,false,true)}
function drawBones(){bones.forEach(drawBone)}
function drawCandle(c){if(c.collected)return;const x=c.x-state.cameraX;ctx.fillStyle="#fff4ff";roundedRect(x,c.y+8,c.w,c.h-8,6,true,false);ctx.strokeStyle="#c16ea9";ctx.lineWidth=2;roundedRect(x,c.y+8,c.w,c.h-8,6,false,true);ctx.fillStyle="#ffbddf";ctx.fillRect(x+5,c.y+12,4,c.h-14);ctx.fillRect(x+12,c.y+14,4,c.h-18);ctx.fillStyle="#ff8200";ctx.beginPath();ctx.moveTo(x+c.w/2,c.y-8);ctx.quadraticCurveTo(x+c.w-2,c.y+8,x+c.w/2,c.y+10);ctx.quadraticCurveTo(x+2,c.y+8,x+c.w/2,c.y-8);ctx.fill();ctx.fillStyle="#ffe36d";ctx.beginPath();ctx.arc(x+c.w/2,c.y+2,5,0,Math.PI*2);ctx.fill()}
function drawCandles(){candles.forEach(drawCandle)}
function drawDog(d){const x=d.x-state.cameraX,y=d.y;ctx.save();ctx.fillStyle=d.color==="brown"?"#9e643e":"#ffffff";ctx.strokeStyle="#272727";ctx.lineWidth=4;roundedRect(x+12,y+10,d.w-16,d.h-10,12,true,true);roundedRect(x,y+14,28,20,12,true,true);ctx.beginPath();ctx.moveTo(x+8,y+13);ctx.lineTo(x+5,y+1);ctx.lineTo(x+16,y+11);ctx.closePath();ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(x+20,y+12);ctx.lineTo(x+19,y+0);ctx.lineTo(x+29,y+11);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillRect(x+18,y+d.h-3,7,10);ctx.fillRect(x+39,y+d.h-3,7,10);ctx.fillStyle="#222";ctx.beginPath();ctx.arc(x+16,y+21,2.7,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(x+23,y+25,3.3,0,Math.PI*2);ctx.fill();if(d.color==="white"){ctx.strokeStyle="#c9c9c9";ctx.lineWidth=2;roundedRect(x+12,y+10,d.w-16,d.h-10,12,false,true);roundedRect(x,y+14,28,20,12,false,true)}ctx.restore()}
function drawDogs(){dogs.forEach(drawDog)}
function drawPlayer(){const x=player.x-state.cameraX,y=player.y,leg=Math.sin(player.anim)*5;ctx.save();ctx.strokeStyle="#1f1f1f";ctx.lineWidth=4;ctx.fillStyle="#f1c94c";ctx.beginPath();ctx.moveTo(x+38,y+12);ctx.quadraticCurveTo(x+62,y+30,x+48,y+72);ctx.lineTo(x+36,y+58);ctx.quadraticCurveTo(x+44,y+34,x+28,y+18);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle="#f4cbb2";ctx.beginPath();ctx.arc(x+28,y+22,16,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle="#f1c94c";ctx.beginPath();ctx.arc(x+28,y+15,18,Math.PI,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillRect(x+10,y+14,34,18);ctx.strokeRect(x+10,y+14,34,18);ctx.fillStyle="#ff70aa";roundedRect(x+14,y+40,30,30,10,true,true);ctx.fillStyle="#f4cbb2";ctx.fillRect(x+8,y+42,6,24);ctx.fillRect(x+44,y+44,6,22);ctx.strokeRect(x+8,y+42,6,24);ctx.strokeRect(x+44,y+44,6,22);ctx.fillStyle="#5d3a7f";ctx.fillRect(x+19,y+70,8,28+leg*.18);ctx.fillRect(x+32,y+70,8,28-leg*.18);ctx.strokeRect(x+19,y+70,8,28+leg*.18);ctx.strokeRect(x+32,y+70,8,28-leg*.18);ctx.fillStyle="#43304a";ctx.fillRect(x+16,y+96,14,8);ctx.fillRect(x+31,y+96,14,8);ctx.strokeRect(x+16,y+96,14,8);ctx.strokeRect(x+31,y+96,14,8);ctx.fillStyle="#222";ctx.beginPath();ctx.arc(x+23,y+22,2.2,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(x+31,y+22,2.2,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(x+27,y+29,5,0.1,Math.PI-.1);ctx.stroke();ctx.restore()}
function drawCaptureScene(){if(state.captureTimer<=0||!state.captureBy)return;const d=state.captureBy,x=d.x-state.cameraX,y=d.y;ctx.save();ctx.strokeStyle="#222";ctx.lineWidth=3;ctx.fillStyle=d.color==="brown"?"#9e643e":"#ffffff";roundedRect(x+10,y-34,52,30,10,true,true);roundedRect(x-2,y-22,24,18,10,true,true);ctx.fillRect(x+18,y-6,7,16);ctx.fillRect(x+34,y-6,7,16);if(d.color==="white"){ctx.strokeStyle="#c9c9c9";ctx.lineWidth=2;roundedRect(x+10,y-34,52,30,10,false,true);roundedRect(x-2,y-22,24,18,10,false,true)}ctx.restore();const bx=x-20,by=y-108;ctx.fillStyle="#fff";ctx.strokeStyle="#333";ctx.lineWidth=4;roundedRect(bx,by,138,58,18,true,true);ctx.beginPath();ctx.moveTo(bx+36,by+58);ctx.lineTo(bx+55,by+72);ctx.lineTo(bx+62,by+56);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle="#4d2751";ctx.font="bold 20px Trebuchet MS";ctx.fillText("Wuff! Her damit!",bx+12,by+34)}
function drawGoal(){const x=goal.x-state.cameraX,y=goal.y;if(!goal.burst){ctx.strokeStyle="#1f3120";ctx.lineWidth=4;ctx.fillStyle="#4f8e43";ctx.beginPath();ctx.moveTo(x+32,y+176);ctx.lineTo(x+24,y+88);ctx.quadraticCurveTo(x+26,y+56,x+42,y+42);ctx.lineTo(x+42,y+18);ctx.quadraticCurveTo(x+55,y+4,x+68,y+18);ctx.lineTo(x+68,y+42);ctx.quadraticCurveTo(x+84,y+56,x+86,y+88);ctx.lineTo(x+78,y+176);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle="rgba(255,255,255,0.16)";ctx.beginPath();ctx.moveTo(x+40,y+34);ctx.quadraticCurveTo(x+50,y+52,x+46,y+154);ctx.lineTo(x+36,y+154);ctx.quadraticCurveTo(x+38,y+60,x+34,y+40);ctx.closePath();ctx.fill();ctx.fillStyle="#e8d48a";roundedRect(x+38,y+8,34,24,8,true,true);ctx.fillStyle="#f0c95a";roundedRect(x+40,y+30,30,14,6,true,true);ctx.fillStyle="#fff8e6";roundedRect(x+32,y+96,46,34,10,true,true);ctx.fillStyle="#d9b24f";ctx.font="bold 14px Trebuchet MS";ctx.fillText("SEKT",x+37,y+117);ctx.fillStyle="rgba(255,255,255,0.12)";ctx.beginPath();ctx.arc(x+56,y+154,18,0,Math.PI*2);ctx.fill()}}
function drawFoamAndConfetti(){state.foam.forEach(p=>{if(p.life<=0)return;const x=p.x-state.cameraX;ctx.fillStyle="#f7f3db";ctx.beginPath();ctx.arc(x,p.y,p.r,0,Math.PI*2);ctx.fill();ctx.strokeStyle="rgba(180,170,120,0.45)";ctx.lineWidth=1;ctx.stroke()});state.confetti.forEach(c=>{const x=c.x-state.cameraX;ctx.save();ctx.translate(x,c.y);ctx.rotate(c.rot);ctx.fillStyle=c.color;ctx.fillRect(-c.size/2,-c.size/2,c.size,c.size*.65);ctx.restore()})}
function drawHud(){ctx.fillStyle="rgba(78,41,86,.9)";roundedRect(18,18,285,84,18,true,false);ctx.fillStyle="#fff";ctx.font="bold 24px Trebuchet MS";ctx.fillText("Kerzen: "+state.collectedDigits.length+"/3",34,52);ctx.font="18px Trebuchet MS";ctx.fillText("Hundeknochen: "+state.bonusBones,34,82);ctx.fillStyle="rgba(78,41,86,.9)";roundedRect(WIDTH-285,18,267,84,18,true,false);ctx.fillStyle="#fff";ctx.font="bold 18px Trebuchet MS";ctx.fillText("Ziel: Sektflasche",WIDTH-258,50);ctx.fillText("nach 3 Kerzen",WIDTH-258,78)}
function drawComicPanel(x,y,w,h,fill,stroke){ctx.fillStyle=fill;roundedRect(x,y,w,h,28,true,false);ctx.strokeStyle=stroke;ctx.lineWidth=8;roundedRect(x,y,w,h,28,false,true);ctx.strokeStyle="rgba(255,148,200,.55)";ctx.lineWidth=4;roundedRect(x+16,y+16,w-32,h-32,22,false,true)}
function drawCake(x,y){ctx.fillStyle="#ffe5a3";roundedRect(x,y,138,54,14,true,false);ctx.fillStyle="#ffb4d7";roundedRect(x,y-28,138,34,14,true,false);[20,62,104].forEach(dx=>{ctx.fillStyle="#fff";ctx.fillRect(x+dx,y-42,10,16);ctx.fillStyle="#ff9a1a";ctx.beginPath();ctx.arc(x+dx+5,y-46,5,0,Math.PI*2);ctx.fill()})}
function drawSpeaker(x,y){ctx.fillStyle="#3f4158";roundedRect(x,y,112,142,18,true,false);ctx.fillStyle="#20222c";ctx.beginPath();ctx.arc(x+56,y+52,29,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(x+56,y+107,17,0,Math.PI*2);ctx.fill();ctx.fillStyle="#fff";ctx.font="bold 16px Trebuchet MS";ctx.fillText("ROCK",x+32,y+18)}
function drawMiniDogs(x,y){const old=state.cameraX;state.cameraX=0;drawDog({x:x,y:y,w:62,h:33,color:"brown"});drawDog({x:x+86,y:y+2,w:62,h:33,color:"white"});state.cameraX=old}
function drawStartOverlay(){ctx.fillStyle="rgba(44,24,50,.55)";ctx.fillRect(0,0,WIDTH,HEIGHT);drawComicPanel(120,92,1040,470,"#fff9fc","#582a5c");drawCake(188,408);drawSpeaker(945,365);drawMiniDogs(894,452);ctx.textAlign="center";ctx.fillStyle="#582a5c";ctx.font="bold 42px Trebuchet MS";ctx.fillText("Liebe Virág!",WIDTH/2,178);ctx.font="28px Trebuchet MS";ctx.fillText("Wir wünschen Dir alles Liebe und Gute zum Geburtstag!",WIDTH/2,238);ctx.fillText("Erst mit Hilfe dieses Spiels bekommst Du die Möglichkeit",WIDTH/2,292);ctx.fillText("Dein Geburtstagsgeschenk zu öffnen.",WIDTH/2,336);ctx.fillText("Wir wünschen Dir viel Spaß :)!",WIDTH/2,396);drawStartButton();ctx.textAlign="left"}
function drawStartButton(){const b=getStartButton(),pulse=1+Math.sin(Date.now()*.006)*.03,w=b.w*pulse,h=b.h*pulse,x=b.x-(w-b.w)/2,y=b.y-(h-b.h)/2;ctx.fillStyle="#ff63a3";roundedRect(x,y,w,h,22,true,false);ctx.strokeStyle="#582a5c";ctx.lineWidth=6;roundedRect(x,y,w,h,22,false,true);ctx.fillStyle="#fff";ctx.textAlign="center";ctx.font="bold 30px Trebuchet MS";ctx.fillText("Spiel starten",WIDTH/2,y+42);ctx.textAlign="left"}
function getStartButton(){return{x:WIDTH/2-155,y:454,w:310,h:66}}
function drawWinOverlay(){ctx.fillStyle="rgba(34,20,40,.58)";ctx.fillRect(0,0,WIDTH,HEIGHT);drawComicPanel(125,105,1030,455,"#fffef8","#4d2751");drawCake(186,408);drawSpeaker(942,372);ctx.textAlign="center";ctx.fillStyle="#4d2751";ctx.font="bold 52px Trebuchet MS";ctx.fillText("Geschafft!",WIDTH/2,185);ctx.font="30px Trebuchet MS";ctx.fillText("Happy Birthday Virág! 🎉",WIDTH/2,245);ctx.fillText("Du hast alle Kerzen gesammelt",WIDTH/2,297);ctx.fillText("und die Sektflasche geknackt!",WIDTH/2,342);ctx.fillStyle="#ff5f9f";roundedRect(WIDTH/2-190,380,380,86,22,true,false);ctx.fillStyle="#fff";ctx.font="bold 60px Trebuchet MS";ctx.fillText(state.collectedDigits.join(" "),WIDTH/2,440);ctx.fillStyle="#4d2751";ctx.font="20px Trebuchet MS";ctx.fillText("Gesammelte Hundeknochen: "+state.bonusBones,WIDTH/2,495);ctx.textAlign="left"}
function render(){drawSky();drawGround();drawPlatforms();drawBones();drawCandles();drawDogs();drawGoal();drawPlayer();drawCaptureScene();drawFoamAndConfetti();drawHud();if(state.mode==="start")drawStartOverlay();if(state.mode==="win")drawWinOverlay()}
function update(){updateDogs();if(state.mode==="playing")updatePlayer();else updateMovingPlatforms();updateParticles()}
function loop(){update();render();requestAnimationFrame(loop)}
function pressJump(){if(state.mode==="start")startGame();if(state.captureTimer<=0)controls.jump=true}
document.addEventListener("keydown",e=>{if(e.code==="ArrowLeft"){controls.left=true;if(state.mode==="start")startGame()}if(e.code==="ArrowRight"){controls.right=true;if(state.mode==="start")startGame()}if(e.code==="Space"||e.code==="ArrowUp"){e.preventDefault();pressJump()}})
document.addEventListener("keyup",e=>{if(e.code==="ArrowLeft")controls.left=false;if(e.code==="ArrowRight")controls.right=false;if(e.code==="Space"||e.code==="ArrowUp")controls.jump=false})
function bindHoldButton(id,onPress,onRelease){const el=document.getElementById(id),start=ev=>{ev.preventDefault();onPress()},end=ev=>{ev.preventDefault();onRelease()};el.addEventListener("touchstart",start,{passive:false});el.addEventListener("touchend",end,{passive:false});el.addEventListener("touchcancel",end,{passive:false});el.addEventListener("mousedown",start);el.addEventListener("mouseup",end);el.addEventListener("mouseleave",end)}
bindHoldButton("leftBtn",()=>{if(state.mode==="start")startGame();controls.left=true},()=>controls.left=false);
bindHoldButton("rightBtn",()=>{if(state.mode==="start")startGame();controls.right=true},()=>controls.right=false);
bindHoldButton("jumpBtn",()=>pressJump(),()=>controls.jump=false);
function pointInStartButton(x,y){const b=getStartButton();return x>=b.x&&x<=b.x+b.w&&y>=b.y&&y<=b.y+b.h}
function canvasToWorld(evX,evY){const rect=canvas.getBoundingClientRect();return{x:(evX-rect.left)*(WIDTH/rect.width),y:(evY-rect.top)*(HEIGHT/rect.height)}}
canvas.addEventListener("click",e=>{if(state.mode!=="start")return;const p=canvasToWorld(e.clientX,e.clientY);if(pointInStartButton(p.x,p.y))startGame()});
canvas.addEventListener("touchstart",e=>{if(state.mode!=="start")return;const t=e.touches[0],p=canvasToWorld(t.clientX,t.clientY);if(pointInStartButton(p.x,p.y))startGame()},{passive:true});
resetPlayerPosition();loop();